### ISSUE TITLE
BCrypt Error with apache Apache/2.4.41 on ubuntu 20.04

### ISSUE THREAD

**Issue by belug23** [dholth/cryptacular#2]
Hi,

we have found a problement with the bcrypt  password manager under Ubuntu 20.04 while using apache and wsgi. The crypt_rn function will always return None and we have no logs of the error.

If we use the python binary there's no problems. I was able to reproduce it with a server install and a desktop install of ubuntu both using apache2 with mod_wsgi.

Our logs about the problem:
```
[wsgi:error]   File "lib/python3.8/site-packages/cryptacular/core/__init__.py", line 102, in check
[wsgi:error]     valid = manager.check(encoded, password)
[wsgi:error]   File "lib/python3.8/site-packages/cryptacular/bcrypt/__init__.py", line 76, in check
[wsgi:error]     raise ValueError('_bcrypt.crypt_rn returned None')
[wsgi:error] ValueError: _bcrypt.crypt_rn returned None
```

Versions:
  -  Ubuntu 20.04.2 LTS
  -  Linux 5.4.0-65-generic
  -  Apache 2.4.41 (Build date 2020-08-12T19:46:17)
  -  Python 3.8.0 (GCC 9.3.0)
  -  mod_wsgi 4.6.8
  -  Cryptacular 1.5.5

**For anyone with the same problem:** At the moment we bypassed the problem by using a custom BCrypt password manager using another BCrypt python module.

**Comment by nandoflorestan** [comment]
I get the exact same exception when I run on Python 3.8.x installed with pyenv on Manjaro Linux.  The code runs fine when I use Python 3.9 from Manjaro Linux, which makes me think my Python 3.8 environment is unable to find the BCrypt library (written in C) used by cryptacular.  I have no idea how to make that work, any help appreciated.

**Comment by dholth** [comment]
I had the same problem. Will let you know if I find a solution. I suppose we could depend on the other package. Tried to avoid using the manylinux1 binary wheel but the necessary crypt header was also missing.

**Comment by dholth** [comment]
It's possible that newer versions of glibc are stricter about what they accept as a (bcrypt) salt...

Or that we have to use libxcrypt instead of the builtin one?

**Comment by dholth** [comment]
p.s. some OS's (even Linux?) can do bcrypt with the crypt() function, and no added cryptacular C extension. So it might be possible for BCPM to use the crypt() function in python stdlib in those cases.

**Comment by dholth** [comment]
Does the 1.6.0 branch fix this problem?
